import { createSlice, PayloadAction } from "@reduxjs/toolkit";

// Define types for blog and course data
export interface Blog {
  id: number;
  comments: { text: string; user_id: number }[];
  content: string;
  course: { course_name: string; id: number };
  created_at: string;
  department: { department_name: string; id: number };
  likes: { user_id: number }[];
  title: string;
  user_id: number;
  username: string;
  // Add other properties specific to a blog if needed
}

interface Course {
  course_name: string;
  id: number;
  // Add other properties specific to a course if needed
}

// Define the type for the blog state
interface BlogState {
  allBlogs: Blog[];
  searchedBlogs: Blog[];
  blogsById:Blog[],
  blogsByDepartment: Blog[]; // Change to Blog[] directly
  coursesByDepartment: Record<string, Course[]>;
  // Add other properties related to blog state if needed
}

// Define the initial state
const initialState: BlogState = {
  allBlogs: [],
  blogsById:[],
  searchedBlogs: [],
  blogsByDepartment: [], // Change to an array directly
  coursesByDepartment: {},
  // Initialize other blog-related properties if any
};

// Create a slice
const blogStateSlice = createSlice({
  name: 'blog',
  initialState,
  reducers: {
    setAllBlogs(state, action: PayloadAction<Blog[]>) {
      state.allBlogs = action.payload;
    },
    setSearchedBlogs(state, action: PayloadAction<Blog[]>) {
      state.searchedBlogs = action.payload;
    },
    setBlogsById(state, action: PayloadAction<Blog[]>) {
      state.blogsById = action.payload;
    },
    setBlogsByDepartment(state, action: PayloadAction<Blog[]>) {
      state.blogsByDepartment = action.payload;
    },
    setCoursesByDepartment(state, action: PayloadAction<{ department: string; courses: Course[] }>) {
      const { department, courses } = action.payload;
      state.coursesByDepartment[department] = courses;
    },
    // Add other reducers for blog state management if needed
  },
});

// Export actions generated by the slice
export const {
  setAllBlogs,
  setSearchedBlogs,
  setBlogsByDepartment,
  setCoursesByDepartment,
  setBlogsById,
  // Other exported actions
} = blogStateSlice.actions;

// Export the reducer
export default blogStateSlice.reducer;
