import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { DepartmentRequest } from "./blogApiSlice";
// Define the type for the department state
interface DepartmentState {
  departmentData: DepartmentRequest | null;
  // Add other properties related to department state if needed
}

// Define the initial state
const initialState: DepartmentState = {
  departmentData: null,
  // Initialize other department-related properties if any
};

// Create a slice
const departmentSlice = createSlice({
  name: 'department',
  initialState,
  reducers: {
    setDepartmentData(state, action: PayloadAction<DepartmentRequest>) {
      state.departmentData = action.payload;
    },
    // Add other reducers for department state management if needed
  },
});

// Export actions generated by the slice
export const { setDepartmentData } = departmentSlice.actions;

// Export the reducer
export default departmentSlice.reducer;
